name: Reusable Integration Tests

on:
  workflow_call:
    inputs:
      platformVersion:
        required: false
        default: 2022.1.4
        type: string

env:
  XDG_CACHE_HOME: "~/.config/"

jobs:
  subtasksList:
    name: Prepare Environment
    runs-on: ubuntu-latest

    steps:

      - name: Fetch Sources
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Cache XDG_CACHE_HOME
        uses: actions/cache@v3
        with:
          path: ${{ env.XDG_CACHE_HOME }}
          key: ${{ runner.os }}-XDG_CACHE_HOME-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-XDG_CACHE_HOME-

      - name: Build and Publish Plugin to MavenLocal
        run: ./gradlew -Pversion="0.0.0" :publishToMavenLocal

      - name: Store Built Plugin
        uses: actions/upload-artifact@v3
        with:
          name: m2-repository
          path: ~/.m2/repository

  integrationTests:
    name: Gradle ${{ matrix.gradleVersion }} @ ${{ matrix.os }}
    needs: subtasksList
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        gradleVersion:
          - "7.3"
          - "7.6.1"
          - "8.0.2"
          - "8.1-rc-3"
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest

    steps:

      - name: Fetch Sources
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      - name: Cache XDG_CACHE_HOME
        uses: actions/cache@v3
        with:
          path: ${{ env.XDG_CACHE_HOME }}
          key: ${{ runner.os }}-XDG_CACHE_HOME-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-XDG_CACHE_HOME-

      - uses: actions/download-artifact@v3
        with:
          name: m2-repository
          path: ~/.m2/repository

      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: ${{ matrix.gradleVersion }}

      # INTEGRATION TESTS
      - name: attaching-plugin-bundled-sources
        working-directory: ${{ github.workspace }}/integration-tests
        env:
          PLATFORM_VERSION: ${{ inputs.platformVersion }}
        run: ./attaching-plugin-bundled-sources/verify.main.kts `which gradle`

      - name: attaching-plugin-sources-from-ide-dist
        working-directory: ${{ github.workspace }}/integration-tests
        env:
          PLATFORM_VERSION: ${{ inputs.platformVersion }}
        run: ./attaching-plugin-sources-from-ide-dist/verify.main.kts `which gradle`

      - name: build-features
        working-directory: ${{ github.workspace }}/integration-tests
        env:
          PLATFORM_VERSION: ${{ inputs.platformVersion }}
        run: ./build-features/verify.main.kts `which gradle`

      - name: classpath
        working-directory: ${{ github.workspace }}/integration-tests
        env:
          PLATFORM_VERSION: ${{ inputs.platformVersion }}
        run: ./classpath/verify.main.kts `which gradle`

      - name: instrumentation-task
        working-directory: ${{ github.workspace }}/integration-tests
        env:
          PLATFORM_VERSION: ${{ inputs.platformVersion }}
        run: ./instrumentation-task/verify.main.kts `which gradle`

      - name: instrumentation-task-disabled
        working-directory: ${{ github.workspace }}/integration-tests
        env:
          PLATFORM_VERSION: ${{ inputs.platformVersion }}
        run: ./instrumentation-task-disabled/verify.main.kts `which gradle`

      - name: jar-manifest-file
        working-directory: ${{ github.workspace }}/integration-tests
        env:
          PLATFORM_VERSION: ${{ inputs.platformVersion }}
        run: ./jar-manifest-file/verify.main.kts `which gradle`

      - name: plugin-xml-patching
        working-directory: ${{ github.workspace }}/integration-tests
        env:
          PLATFORM_VERSION: ${{ inputs.platformVersion }}
        run: ./plugin-xml-patching/verify.main.kts `which gradle`

      - name: test-classpath-project-resources
        working-directory: ${{ github.workspace }}/integration-tests
        env:
          PLATFORM_VERSION: ${{ inputs.platformVersion }}
        run: ./test-classpath-project-resources/verify.main.kts `which gradle`

      - name: throwing-exceptions
        working-directory: ${{ github.workspace }}/integration-tests
        env:
          PLATFORM_VERSION: ${{ inputs.platformVersion }}
        run: ./throwing-exceptions/verify.main.kts `which gradle`

      - name: verify-plugin-configuration
        if: false
        working-directory: ${{ github.workspace }}/integration-tests
        env:
          PLATFORM_VERSION: ${{ inputs.platformVersion }}
        run: ./verify-plugin-configuration/verify.main.kts `which gradle`
